<script type="text/javascript" src="/JavaScript/Frameworks/angular.min.js"></script>
<script type="text/javascript" src="/JavaScript/Frameworks/angular-route.min.js"></script>
<script type="text/javascript" src="/JavaScript/Frameworks/ui-bootstrap-tpls-1.2.5.min.js"></script>
<script type="text/javascript" src="/JavaScript/ApplicationsJS/SubmitAnApplication/applicationRun.js"></script>
<script type="text/javascript" src="/JavaScript/ApplicationsJS/SubmitAnApplication/constants.js"></script>
<script type="text/javascript" src="/JavaScript/ApplicationsJS/SubmitAnApplication/Services/applicationService.js"></script>
<script type="text/javascript" src="/JavaScript/ApplicationsJS/SubmitAnApplication/Controllers/controllerStep1.js"></script>
<script type="text/javascript" src="/JavaScript/ApplicationsJS/SubmitAnApplication/Controllers/controllerStep2.js"></script>
<script type="text/javascript" src="/JavaScript/ApplicationsJS/SubmitAnApplication/Controllers/controllerStep3.js"></script>
<script type="text/javascript" src="/JavaScript/ApplicationsJS/SubmitAnApplication/Controllers/controllerModalAddPublication.js"></script>
<script type="text/javascript" src="/JavaScript/ShareFolderApplication/Directives/logoApplicationValidator.js"></script>
<script type="text/javascript" src="/JavaScript/ShareFolderApplication/Directives/nameApplicationValidator.js"></script>